/**
 * Bake `html2hwpx`'s HWPX template into a source module.
 *
 * The library reads this template off its own package directory with `fs` every
 * time it writes a document. That is the single reason its exporter cannot run
 * in a browser — everything else on the conversion path is pure string work.
 * Embedding the files removes the filesystem from the export path entirely, so
 * one implementation serves the browser and Node alike, and no bundler has to be
 * told to keep the library external.
 *
 * Regenerate after bumping `html2hwpx`:
 *
 *     npm run generate:template -w @samugen/hwpx-convert
 *
 * The output is committed so a plain `npm ci` needs no generation step.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = fileURLToPath(new URL('.', import.meta.url))
const templateDir = fileURLToPath(
  new URL('../../../node_modules/html2hwpx/template', import.meta.url),
)
const outFile = join(here, '..', 'src', 'template-data.ts')

/** Files the exporter regenerates per document; the template's copies are never shipped. */
const GENERATED = new Set(['Contents/header.xml', 'Contents/section0.xml', 'Contents/content.hpf'])

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) walk(full, out)
    else out.push(full)
  }
  return out
}

/** Safe inside a template literal: backticks, backslashes and `${` would otherwise interpolate. */
function asTemplateLiteral(text: string): string {
  return '`' + text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`'
}

const paths = walk(templateDir)
  .map((p) => relative(templateDir, p).split(/[\\/]/).join('/'))
  .sort()

const headerXml = readFileSync(join(templateDir, 'Contents/header.xml'), 'utf8')
const contentHpf = readFileSync(join(templateDir, 'Contents/content.hpf'), 'utf8')

// The template's section0.xml is exactly the section-properties paragraph and
// nothing else, which is what every generated document must open with. Taking it
// from the template rather than restating it keeps the two in step.
const sectionXml = readFileSync(join(templateDir, 'Contents/section0.xml'), 'utf8')
const preamble = /<hs:sec[^>]*>([\s\S]*)<\/hs:sec>/.exec(sectionXml)?.[1]
if (!preamble) throw new Error('template section0.xml has no <hs:sec> body to take the secPr from')

const packageFiles = paths
  .filter((p) => !GENERATED.has(p))
  .map((p) => {
    const base64 = readFileSync(join(templateDir, p)).toString('base64')
    return `  '${p}': '${base64}',`
  })
  .join('\n')

const source = `/**
 * GENERATED by scripts/generate-template.ts — do not edit by hand.
 *
 * The HWPX package skeleton, taken from html2hwpx's own template directory so a
 * document can be written without a filesystem. See the generator for why.
 *
 * Source: html2hwpx@${JSON.parse(readFileSync(fileURLToPath(new URL('../../../node_modules/html2hwpx/package.json', import.meta.url)), 'utf8')).version}
 */

/** Style tables the converter reads and rewrites; shipped as \`Contents/header.xml\`. */
export const TEMPLATE_HEADER_XML = ${asTemplateLiteral(headerXml)}

/** Package manifest; shipped as \`Contents/content.hpf\`. */
export const TEMPLATE_CONTENT_HPF = ${asTemplateLiteral(contentHpf)}

/**
 * The section-properties paragraph every document opens with — page size,
 * margins, footnote and border settings — which the body is appended after.
 */
export const TEMPLATE_SECTION_PREAMBLE = ${asTemplateLiteral(preamble)}

/**
 * Every remaining package file, base64-encoded, keyed by its path in the zip.
 *
 * Excludes the three parts the exporter regenerates per document
 * (\`header.xml\`, \`section0.xml\`, \`content.hpf\`).
 */
export const TEMPLATE_PACKAGE_FILES: Readonly<Record<string, string>> = {
${packageFiles}
}
`

writeFileSync(outFile, source)
console.log(`wrote ${relative(process.cwd(), outFile)} (${paths.length} template files)`)
